import java.awt.Color;
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.*;

import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class MainMenuPanel extends JPanel implements ActionListener{

	// Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration
    
    /**
     * Creates new form MainMenuPlay
     */
    public MainMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                        
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ButtonGroup group = new ButtonGroup();
        
        group.add(jToggleButton1);
        group.add(jToggleButton2);
        group.add(jToggleButton3);

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        
        jToggleButton1.setSelected(true);
        //jToggleButton1.setBackground(Color.yellow);
    	jToggleButton2.setBackground(Color.gray);
    	jToggleButton3.setBackground(Color.gray);
    	
        jToggleButton1.setText("Play");
        jToggleButton1.addActionListener(this);

        jToggleButton2.setText("Customize");
        jToggleButton2.addActionListener(this);

        jToggleButton3.setText("Extras");
        jToggleButton3.addActionListener(this);
    	
    	jLabel1.setIcon(new javax.swing.ImageIcon("images/champions.png")); // NOI18N
    	jLabel1.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e) {
            	jLabel1(e);
            }
			@Override
			public void mouseEntered(MouseEvent arg0) {}
			@Override
			public void mouseExited(MouseEvent arg0) {}
			@Override
			public void mousePressed(MouseEvent arg0) {}
			@Override
			public void mouseReleased(MouseEvent arg0) {}
        });
        jLabel2.setIcon(new javax.swing.ImageIcon("images/continue.jpg")); // NOI18N
        jLabel2.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e) {
            	jLabel2(e);
            }
			@Override
			public void mouseEntered(MouseEvent arg0) {}
			@Override
			public void mouseExited(MouseEvent arg0) {}
			@Override
			public void mousePressed(MouseEvent arg0) {}
			@Override
			public void mouseReleased(MouseEvent arg0) {}
        });
        jLabel3.setIcon(new javax.swing.ImageIcon("images/multiplayer.jpg")); // NOI18N
        jLabel3.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e) {
            	jLabel3(e);
            }
			@Override
			public void mouseEntered(MouseEvent arg0) {}
			@Override
			public void mouseExited(MouseEvent arg0) {}
			@Override
			public void mousePressed(MouseEvent arg0) {}
			@Override
			public void mouseReleased(MouseEvent arg0) {}
        });
        jLabel4.setIcon(new javax.swing.ImageIcon("images/training.jpg")); // NOI18N
        jLabel4.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e) {
            	jLabel4(e);
            }
			@Override
			public void mouseEntered(MouseEvent arg0) {}
			@Override
			public void mouseExited(MouseEvent arg0) {}
			@Override
			public void mousePressed(MouseEvent arg0) {}
			@Override
			public void mouseReleased(MouseEvent arg0) {}
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent arg0) {
				TestMain.frame.dispose();
				
			}	
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }
    
    public void actionPerformed(ActionEvent ev){
    	if ( jToggleButton1.isSelected() ) {
        	jToggleButton1.setBackground(Color.yellow);
        	jToggleButton2.setBackground(Color.gray);
        	jToggleButton3.setBackground(Color.gray);
        	
        	jLabel1.setIcon(new javax.swing.ImageIcon("images/champions.png")); // NOI18N
            jLabel2.setIcon(new javax.swing.ImageIcon("images/continue.jpg")); // NOI18N
            jLabel3.setIcon(new javax.swing.ImageIcon("images/multiplayer.jpg")); // NOI18N
            jLabel4.setIcon(new javax.swing.ImageIcon("images/training.jpg")); // NOI18N
        }
    	
    	if ( jToggleButton2.isSelected() ) {
    		jToggleButton1.setBackground(Color.gray);
        	jToggleButton2.setBackground(Color.yellow);
        	jToggleButton3.setBackground(Color.gray);
        	
        	jLabel1.setIcon(new javax.swing.ImageIcon("images/setting.jpg")); // NOI18N
            jLabel2.setIcon(new javax.swing.ImageIcon("images/sound.jpg")); // NOI18N
            jLabel3.setIcon(new javax.swing.ImageIcon("images/stadium.jpg")); // NOI18N
            jLabel4.setIcon(new javax.swing.ImageIcon("images/keyboard.jpg")); // NOI18N
        }
    	
    	if ( jToggleButton3.isSelected() ) {
    		jToggleButton1.setBackground(Color.gray);
        	jToggleButton2.setBackground(Color.gray);
        	jToggleButton3.setBackground(Color.yellow);
        	
    		jLabel1.setIcon(new javax.swing.ImageIcon("images/cre1.png")); // NOI18N
            jLabel2.setIcon(new javax.swing.ImageIcon("images/asd.jpg")); // NOI18N
            jLabel3.setIcon(new javax.swing.ImageIcon("images/cre2.png")); // NOI18N
            jLabel4.setIcon(new javax.swing.ImageIcon("images/inst.jpg")); // NOI18N
        }
    	
    	repaint();
    }
    
    public void jLabel1(MouseEvent e){
    	Game g = new Game();
    	try {
           FileInputStream fileIn = new FileInputStream("data.ser");
           ObjectInputStream in = new ObjectInputStream(fileIn);
           g = (Game) in.readObject();
           in.close();
           fileIn.close();
        }catch(IOException i) {
           i.printStackTrace();
           return;
        }catch(ClassNotFoundException c) {
           System.out.println("Game class not found");
           c.printStackTrace();
           return;
        }
    	
    	if ( jToggleButton1.isSelected()){
    		g.setChampions(true);
        	g.setMainMenuPanel(false);
    	}
    	if ( jToggleButton2.isSelected()){
    		g.setSettings(true);
        	g.setMainMenuPanel(false);
    	}
    	if ( jToggleButton3.isSelected()){
    		g.setCredits(true);
        	g.setMainMenuPanel(false);
    	}
    	
    	try {
            FileOutputStream fileOut =
            new FileOutputStream("data.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(g);
            out.close();
            fileOut.close();
            System.out.println("Serialized data is saved in data.ser");
         }catch(IOException i) {
            i.printStackTrace();
         }
    }
    
    public void jLabel2(MouseEvent e){
    	Game g = new Game();
    	try {
           FileInputStream fileIn = new FileInputStream("data.ser");
           ObjectInputStream in = new ObjectInputStream(fileIn);
           g = (Game) in.readObject();
           in.close();
           fileIn.close();
        }catch(IOException i) {
           i.printStackTrace();
           return;
        }catch(ClassNotFoundException c) {
           System.out.println("Game class not found");
           c.printStackTrace();
           return;
        }
    	
    	if ( jToggleButton1.isSelected()){
    		g.setConti(true);
        	g.setMainMenuPanel(false);
    	}
    	if ( jToggleButton2.isSelected()){
    		g.setSound(true);
        	g.setMainMenuPanel(false);
    	}
    	if ( jToggleButton3.isSelected()){
    		// do nothing
    	}
    	
    	try {
            FileOutputStream fileOut =
            new FileOutputStream("data.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(g);
            out.close();
            fileOut.close();
            System.out.println("Serialized data is saved in data.ser");
         }catch(IOException i) {
            i.printStackTrace();
         }
    }
    
    public void jLabel3(MouseEvent e){
    	Game g = new Game();
    	try {
           FileInputStream fileIn = new FileInputStream("data.ser");
           ObjectInputStream in = new ObjectInputStream(fileIn);
           g = (Game) in.readObject();
           in.close();
           fileIn.close();
        }catch(IOException i) {
           i.printStackTrace();
           return;
        }catch(ClassNotFoundException c) {
           System.out.println("Game class not found");
           c.printStackTrace();
           return;
        }
    	
    	if ( jToggleButton1.isSelected()){
    		g.setMultiplayer(true);
        	g.setMainMenuPanel(false);
    	}
    	if ( jToggleButton2.isSelected()){
    		g.setBallStadium(true);
        	g.setMainMenuPanel(false);
    	}
    	if ( jToggleButton3.isSelected()){
    		g.setCredits(true);
        	g.setMainMenuPanel(false);
    	}
    	
    	try {
            FileOutputStream fileOut =
            new FileOutputStream("data.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(g);
            out.close();
            fileOut.close();
            System.out.println("Serialized data is saved in data.ser");
         }catch(IOException i) {
            i.printStackTrace();
         }
    }
    
    public void jLabel4(MouseEvent e){
    	Game g = new Game();
    	try {
           FileInputStream fileIn = new FileInputStream("data.ser");
           ObjectInputStream in = new ObjectInputStream(fileIn);
           g = (Game) in.readObject();
           in.close();
           fileIn.close();
        }catch(IOException i) {
           i.printStackTrace();
           return;
        }catch(ClassNotFoundException c) {
           System.out.println("Game class not found");
           c.printStackTrace();
           return;
        }
    	
    	if ( jToggleButton1.isSelected()){
    		g.setTraining(true);
        	g.setMainMenuPanel(false);
    	}
    	if ( jToggleButton2.isSelected()){
    		g.setKeyboard(true);
        	g.setMainMenuPanel(false);
    	}
    	if ( jToggleButton3.isSelected()){
    		g.setInst(true);
        	g.setMainMenuPanel(false);
    	}
    	
    	try {
            FileOutputStream fileOut =
            new FileOutputStream("data.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(g);
            out.close();
            fileOut.close();
            System.out.println("Serialized data is saved in data.ser");
         }catch(IOException i) {
            i.printStackTrace();
         }
    }
            
}
